FROM openjdk:17

COPY ./target/NotificationService-0.0.1-SNAPSHOT.jar /app.jar/NotificationService.jar

WORKDIR /app

EXPOSE 8082

# ENTRYPOINT ["java", "-jar", "/app.jar"]
CMD ["java", "-jar", "NotificationService.jar"]
